# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdPgCSh48EvUlf6gpMbefkONUw6G3J1S
"""

# Assignment: Research & Development / AI
# Task: Find unknown parameters in the given parametric curve
# Student: Dharani Malar


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import least_squares


# Step 1: Load the dataset

df = pd.read_csv("xy_data.csv")

# Detect columns
cols = [c.lower().strip() for c in df.columns]
df.columns = cols

# If 't' is missing, generate it between 6 and 60
if 't' in df.columns:
    t = df['t'].values
else:
    t = np.linspace(6, 60, len(df))

# Extract x and y
x_col = next((c for c in cols if 'x' in c), None)
y_col = next((c for c in cols if 'y' in c), None)

if x_col is None or y_col is None:
    raise ValueError("CSV must contain x and y columns!")

x_data = df[x_col].values
y_data = df[y_col].values

# Step 2: Define the parametric model

def model(params, t):
    theta, M, X = params
    theta_rad = np.deg2rad(theta)
    x = t * np.cos(theta_rad) - np.exp(M * np.abs(t)) * np.sin(0.3 * t) * np.sin(theta_rad) + X
    y = 42 + t * np.sin(theta_rad) + np.exp(M * np.abs(t)) * np.sin(0.3 * t) * np.cos(theta_rad)
    return x, y


# Step 3: Define residuals

def residuals(params, t, x_data, y_data):
    x_pred, y_pred = model(params, t)
    return np.concatenate([(x_pred - x_data), (y_pred - y_data)])


# Step 4: Perform least-squares optimization

initial_guess = [20, 0.01, 40]            # [θ, M, X]
bounds = ([0, -0.1, 0], [90, 0.1, 100])  # Parameter limits

result = least_squares(residuals, initial_guess, bounds=bounds, args=(t, x_data, y_data))

theta_opt, M_opt, X_opt = result.x


# Step 5: Display optimized parameters

print("===============================================")
print("          Optimized Parameters Found")
print("===============================================")
print(f"θ (theta) : {theta_opt:.4f}°")
print(f"M          : {M_opt:.6f}")
print(f"X          : {X_opt:.4f}")
print("===============================================")

# ----------------------------------------------------------
# Step 6: Plot results
# ----------------------------------------------------------
x_fit, y_fit = model(result.x, t)

plt.figure(figsize=(8,6))
plt.plot(x_data, y_data, 'bo', markersize=3, label='Original Data')
plt.plot(x_fit, y_fit, 'r-', linewidth=2, label='Fitted Curve')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Parametric Curve Fitting Result')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# Step 7: Save results

fit_df = pd.DataFrame({
    't': t,
    'x_data': x_data,
    'x_fit': x_fit,
    'y_data': y_data,
    'y_fit': y_fit
})
fit_df.to_csv("fitted_results.csv", index=False)
print("Fitted results saved successfully as 'fitted_results.csv'")